name: TypeART-CI

on:
  push:
    branches: [ master, devel ]
  pull_request:

jobs:
  build-and-run-test:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2

      - name: Setup LLVM repository
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main' -y
          sudo apt-get update -q

      - name: Install LLVM
        run: sudo apt-get install libllvm10 llvm-10 llvm-10-dev

      - name: Install Clang
        run: sudo apt-get install clang-10 clang-tidy-10

      - name: Install OpenMPI
        run: sudo apt-get install libopenmpi-dev openmpi-bin

      - name: Setup env
        run: |
          sudo ln -f -s /usr/bin/clang-10 /usr/bin/clang
          sudo ln -f -s /usr/bin/clang++-10 /usr/bin/clang++
          sudo ln -f -s /usr/bin/opt-10 /usr/bin/opt
          sudo ln -f -s /usr/bin/FileCheck-10 /usr/bin/FileCheck
          sudo ln -f -s /usr/bin/llc-10 /usr/bin/llc
          sudo ln -f -s /usr/bin/clang-tidy-10 /usr/bin/clang-tidy
          echo "CC=clang-10" >> $GITHUB_ENV
          echo "CXX=clang++-10" >> $GITHUB_ENV
          echo "EXTERNAL_LIT=/usr/lib/llvm-10/build/utils/lit/lit.py" >> $GITHUB_ENV

      - name: Build TypeART
        run: |
          cmake -B build -DTEST_CONFIG=ON -DLLVM_EXTERNAL_LIT=${EXTERNAL_LIT}
          cmake --build build --parallel

      - name: Test TypeART
        run: cmake --build build --target test -- ARGS=-VV

      - name: Build TypeART Release
        run: |
          cmake -B build_lulesh -DCMAKE_BUILD_TYPE=Release -DMPI_INTERCEPT_LIB=ON -DSHOW_STATS=ON
          cmake --build build_lulesh --parallel

      - name: Test TypeART on lulesh
        working-directory: build_lulesh
        run: ctest -V -R lulesh -O lulesh2.0_build.log
        
      - name: Prepare lulesh artifact
        run: |
          mkdir artifact_lulesh
          mv build_lulesh/lulesh2.0_build.log artifact_lulesh/
          mv test/lulesh/lulesh2.0_out.log artifact_lulesh/
          mv test/lulesh/types.yaml artifact_lulesh/lulesh2.0_types.yaml

      - name: Upload lulesh test artifact
        uses: actions/upload-artifact@v1
        with:
          name: typeart-lulesh-archive
          path: artifact_lulesh
        
